# Generated by Django 4.2.27 on 2025-12-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_book_total_rental'),
        ('lms_app', '0005_book_total_rental'),
    ]

    operations = [
    ]
